### ISSUE TITLE
Digit Detection fails after training from scratch (or fine tuning)

### ISSUE THREAD

**Issue by nealchecka** [penny4860/YOLO-detector#26]
Hi,

Digit detection using the pretrained weight file works fine with the weights.h5 file you provided. When I try to train from scratch or fine tune (even with just 2 images you included as your README described), training completes just fine; however, when I evaluate using the evaluate.py script or detection_example notebook, I get the following error when loading the weights:

Traceback (most recent call last):
  File "evaluate.py", line 56, in <module>
    yolo.load_weights(args.weights)
  File "/home/nchecka/Code/ssocr/Yolo-digit-detector/yolo/frontend.py", line 71, in load_weights
    self._yolo_network.load_weights(weight_path, by_name=by_name)
  File "/home/nchecka/Code/ssocr/Yolo-digit-detector/yolo/backend/network.py", line 58, in load_weights
    self._model.load_weights(weight_path, by_name=by_name)
  File "/home/nchecka/.virtualenvs/cvml/lib/python3.5/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/nchecka/.virtualenvs/cvml/lib/python3.5/site-packages/keras/engine/topology.py", line 3142, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/nchecka/.virtualenvs/cvml/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2247, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/nchecka/.virtualenvs/cvml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/nchecka/.virtualenvs/cvml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (30, 2048, 1, 1) for Tensor 'Placeholder_318:0', which has shape '(1, 1, 2048, 75)'

Am I missing something? I'm using keras 2.1.1 and tensorflow 1.2.1

**Comment by penny4860** [comment]
I have too little information to help you. Could you attach the learned weight file?

**Comment by nealchecka** [comment]
Thank you for your prompt reply. The weight file can be found here:

https://drive.google.com/drive/folders/1rXtwRHiuPNTRc0pD_3kKNk-1Z7jOov15?usp=sharing

**Comment by penny4860** [comment]
In the attached weight file, I confirmed that the error I mentioned is occurring. But I do not know why this is happening.

**Comment by chupibk** [comment]
@nealchecka
That weight file causes the problem. 
Please download another weight file given by @penny4860 
https://drive.google.com/drive/folders/1Lg3eAPC39G9GwVTCH3XzF73Eok-N-dER

**Comment by ericstephenszpaper** [comment]
We have the same error trying to train with our own data sets.
