### ISSUE TITLE
 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hasantha-nirmal** [penny4860/YOLO-detector#48]
Dear Sir,

I'm having this issue when I tried to run the pretrained weights or my owned trained weights.

'AttributeError: 'str' object has no attribute 'decode'

Is the error I finally getting. Your advice would be much appreciated.
Thanks

Loading pre-trained weights in svhn/weights.h5
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    yolo.load_weights(config['pretrained']['full'], by_name=True)
  File "/home/hasantha/Documents/Yolo-digit-detector-master/yolo/frontend.py", line 71, in load_weights
    self._yolo_network.load_weights(weight_path, by_name=by_name)
  File "/home/hasantha/Documents/Yolo-digit-detector-master/yolo/backend/network.py", line 58, in load_weights
    self._model.load_weights(weight_path, by_name=by_name)
  File "/home/hasantha/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py", line 2620, in load_weights
    load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/hasantha/anaconda3/envs/yolo/lib/python3.6/site-packages/keras/engine/topology.py", line 3161, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by btemel** [comment]
I dropped the decode('utf-8') part but that gave me another bug.
You can see the link that has solution: https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error

Now I am getting ValueError: Cannot feed value of shape (30, 2048, 1, 1) for Tensor 'Placeholder_318:0', which has shape '(1, 1, 2048, 75)'
Thanks

**Comment by hasantha-nirmal** [comment]
Thanks for the help. Yes I have tried that too. But it gives that error code as you mentioned . But I think this will help for some extent.

https://www.kaggle.com/tustunkok/license-plate-detection

This repository describes a similar approach for localizing objects from regular cnn. ( I couldn't achieve this btw, hope you could figure this easily)

**Comment by Edvard88** [comment]
I've solved it, thanks to
https://github.com/keras-team/keras/issues/14265#issuecomment-720376773
